"""postal address

Revision ID: 21de95bab20c
Revises: fd0eeb2d6cc0
Create Date: 2023-05-30 09:33:40.222726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21de95bab20c'
down_revision = 'fd0eeb2d6cc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
