"""empty message

Revision ID: 2aaf94acae1d
Revises: 5a64c70ee883
Create Date: 2022-11-13 19:11:19.102773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaf94acae1d'
down_revision = '5a64c70ee883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xumm_payload', sa.Column('is_signed', sa.Integer(), nullable=True))
    op.add_column('xumm_payload', sa.Column('txid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xumm_payload', 'txid')
    op.drop_column('xumm_payload', 'is_signed')
    # ### end Alembic commands ###
