"""postal address

Revision ID: 4143c8626f02
Revises: 8f717066c909
Create Date: 2023-05-25 17:11:06.735388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4143c8626f02'
down_revision = '8f717066c909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('well_known_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name='wallet_address_address_id_fkey'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name='wallet_address_wallet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_address_pkey')
    )
    # ### end Alembic commands ###
