"""address add wallet

Revision ID: 59c4fe7435dc
Revises: 
Create Date: 2023-02-28 16:04:51.065575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c4fe7435dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('address', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'wallet_id')
    # ### end Alembic commands ###
