"""empty message

Revision ID: 5a64c70ee883
Revises: ab87ebcaf6a9
Create Date: 2022-11-13 15:52:52.823149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a64c70ee883'
down_revision = 'ab87ebcaf6a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_item',
    sa.Column('payment_item_id', sa.Integer(), nullable=False),
    sa.Column('fiat_i8n_currency', sa.String(length=3), nullable=True),
    sa.Column('fiat_i8n_price', sa.Float(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('sku_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('payment_item_id')
    )
    op.create_table('xumm_payload',
    sa.Column('xumm_payload_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=16000), nullable=True),
    sa.Column('webhook_body', sa.String(length=16000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payload_uuidv4', sa.String(length=36), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('payment_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_item_id'], ['payment_item.payment_item_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('xumm_payload_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xumm_payload')
    op.drop_table('payment_item')
    # ### end Alembic commands ###
