"""wallet account

Revision ID: 8f717066c909
Revises: 541c527041cf
Create Date: 2023-05-25 16:26:31.742604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f717066c909'
down_revision = '541c527041cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name='account_address_address_id_fkey'),
    sa.ForeignKeyConstraint(['customer_account_id'], ['customer_account.id'], name='account_address_customer_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_address_pkey')
    )
    # ### end Alembic commands ###
