"""empty message

Revision ID: 904c3b53e206
Revises: 2aaf94acae1d
Create Date: 2022-11-14 12:56:32.574722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904c3b53e206'
down_revision = '2aaf94acae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payment_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_item_id'], ['payment_item.payment_item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_uploads')
    # ### end Alembic commands ###
