"""add wallet id

Revision ID: 9fa6a295928d
Revises: 59c4fe7435dc
Create Date: 2023-02-28 16:08:15.055657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa6a295928d'
down_revision = '59c4fe7435dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_item', 'wallet', ['wallet_id'], ['id'])
    op.add_column('order_invoice', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_invoice', 'wallet', ['wallet_id'], ['id'])
    op.add_column('order_item', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_item', 'wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'wallet_id')
    op.drop_constraint(None, 'order_invoice', type_='foreignkey')
    op.drop_column('order_invoice', 'wallet_id')
    op.drop_constraint(None, 'inventory_item', type_='foreignkey')
    op.drop_column('inventory_item', 'wallet_id')
    # ### end Alembic commands ###
