"""empty message

Revision ID: ab87ebcaf6a9
Revises: be10163830d1
Create Date: 2022-08-23 13:19:31.945703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab87ebcaf6a9'
down_revision = 'be10163830d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('seed', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('private_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('classic_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'classic_address')
    op.drop_column('wallet', 'public_key')
    op.drop_column('wallet', 'private_key')
    op.drop_column('wallet', 'seed')
    # ### end Alembic commands ###
