"""add xurl flag

Revision ID: ae0c30506def
Revises: 9fa6a295928d
Create Date: 2023-03-02 18:06:11.699988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0c30506def'
down_revision = '9fa6a295928d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_account_billing_address_id_fkey', 'customer_account', type_='foreignkey')
    op.drop_column('customer_account', 'billing_address_id')
    op.add_column('payment_item', sa.Column('is_xurl_item', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_item', 'is_xurl_item')
    op.add_column('customer_account', sa.Column('billing_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('customer_account_billing_address_id_fkey', 'customer_account', 'address', ['billing_address_id'], ['id'])
    # ### end Alembic commands ###
