"""nft_fields

Revision ID: fd0eeb2d6cc0
Revises: 071e2bbcf793
Create Date: 2023-05-30 09:10:18.135774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0eeb2d6cc0'
down_revision = '071e2bbcf793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'street_address_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('postal_address', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('postal_address', sa.Column('nft_token_id', sa.String(length=64), nullable=True))
    op.add_column('postal_address', sa.Column('nft_token_uri', sa.String(length=256), nullable=True))
    op.add_column('postal_address', sa.Column('nft_token_tx_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postal_address', 'nft_token_tx_hash')
    op.drop_column('postal_address', 'nft_token_uri')
    op.drop_column('postal_address', 'nft_token_id')
    op.drop_column('postal_address', 'status')
    op.alter_column('address', 'street_address_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
