@startuml xurl_usecase

skinparam usecase {
    BackgroundColor<< xInvoice >> #ffabb0
}

package "xURL xumm app" {
    (Scans xApp OAuth2 QR) as xAppLogin
    (Signs xApp OAuth2 QR) as xAppSign 
    (Scans Payment xURL) as xAppxURLScan
    (Sign Payment Payload) as xAppSignPayment
}
note left of xAppLogin
    xApp OAuth2 QR
    contains xApp URL
    and xApp Callback URL
end note

package "xURL Backend (xurlpay.org)" {
    (Login to xURL Backend\nusing xumm Pkce) as xuLoginBackend
    (Handle xURL Deeplink Request) as xuHandleDeeplink
    (Creates xURL) as xuCreateXurl
    (Generate xApp Payment Payload) as xuGeneratePayload
    (Perform Orchestration or\nFiat Conversion) as xuOrchestrate
    (Use LookupRef to Determine State) as xLookupRef
    (POST Stateful Reference of LookupRef) as (PostxURL)
    (Redirect to xApp with Payload) as xuRedirect
}


'oath login
Requestor --> xAppLogin
xAppLogin -> xAppSign
xAppSign --> xuLoginBackend

' create xurl
Requestor-->xuCreateXurl
note right of xuCreateXurl
    wallet user creates PaymentItem
    that is referenced by xURL in the
    xurlpay.org xApp backend
end note

'pay xurl
Payer --> xAppxURLScan
Payer --> xAppSignPayment
xAppxURLScan-->xuHandleDeeplink
xuHandleDeeplink->xLookupRef
xuHandleDeeplink-->xuOrchestrate
xuHandleDeeplink-->xuGeneratePayload

xuGeneratePayload->xuRedirect

note "the payer uses xumm\nto sign the transaction" as N2
xuRedirect ... N2
N2 ... xAppSignPayment



@enduml



