@startuml xurl_usecase

skinparam usecase {
    BackgroundColor<< xInvoice >> #ffabb0
}

package "xURL xumm app" {
    (Scans xURL)
    (Sign Payment Payload) as (SignPayment)
}
note right
this is the xumm wallet 
that signs and pays the 
invoice
end note

package "xURL Backend (xurlpay.org)" {
    (Handle xURL Request)
    (Creates xURL)
    (Generate xApp Payment Payload) as (GeneratePayload)
    (Perform Orchestration or\nFiat Conversion) as (Orchestrate)
}

' Requestor-->(Creates xURL)
' (Creates xURL)-->(POST Stateful Reference)

' Payer-->(Scans xURL)
' (Scans xURL)-->(GET Stateful Reference)
' (GET Stateful Reference)-->(Orchestrate)
' (GET Stateful Reference)-->(GenerateInvoice)

' Payer-->(PayInvoice)
' (PayInvoice)-->(GET Callback)

' note "these are the same use\ncase as xInvoice " as N2
' (GenerateInvoice) .. N2
' N2 .. (PayInvoice)

@enduml



